# Generated by Django 3.1.2 on 2020-10-07 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkUser_id', models.IntegerField()),
                ('name', models.TextField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters.')])),
                ('last_name', models.TextField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters.')])),
                ('document_number', models.IntegerField(max_length=10)),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=250)),
                ('address', models.TextField(max_length=50)),
                ('gender', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('prefiero_no_decirlo', 'Prefiero_no_decirlo'), ('otro', 'Otro')], max_length=19)),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0)),
            ],
        ),
    ]
