# Generated by Django 3.1.1 on 2020-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201007_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('reseller', models.TextField(max_length=200)),
                ('element_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(),
        ),
    ]
