# Generated by Django 3.1.1 on 2020-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201007_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('scheduled_date', models.DateTimeField()),
                ('approved', models.BooleanField()),
                ('service_type', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('fkUser_int', models.IntegerField()),
            ],
        ),
    ]
