# Generated by Django 3.1.1 on 2020-10-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField()),
                ('realization_date', models.DateTimeField()),
                ('fkAssignment_worker', models.IntegerField(default=0)),
                ('fkElement_id', models.IntegerField(default=0)),
                ('fkTask_status', models.IntegerField(default=0)),
            ],
        ),
    ]
