# Generated by Django 3.1.2 on 2020-10-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201010_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='zone',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_log',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
