# Generated by Django 3.1.2 on 2020-10-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201010_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='zone',
        ),
    ]
