# Generated by Django 3.1.1 on 2020-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_inventory_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_log',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='realization_date',
            field=models.DateField(),
        ),
    ]
