# Generated by Django 3.1.2 on 2020-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_requestquotation_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='time_range',
            field=models.TextField(choices=[('8:00 - 9:30', 1), ('10:00 - 11:30', 2), ('13:00 - 14:30', 3), ('15:00 - 16:30', 4), ('17:00 - 18:30', 5)], max_length=13),
        ),
    ]
