# Generated by Django 3.1.2 on 2020-10-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201016_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_log',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
