# Generated by Django 3.1.2 on 2020-10-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201016_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkAssignment_worker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkElement_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkTask_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='realization_date',
            field=models.DateTimeField(),
        ),
    ]
