# Generated by Django 3.1.2 on 2020-10-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201016_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[('admin', 1), ('client', 2), ('employee', 3)], default=0),
        ),
    ]
