# Generated by Django 3.1.2 on 2020-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201016_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('admin', 1), ('client', 2), ('employee', 3)], max_length=8),
        ),
    ]
