# Generated by Django 3.1.2 on 2020-10-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201016_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fkElement_id',
        ),
        migrations.AddField(
            model_name='element',
            name='fkInventory_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_id', to='api.inventory'),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='fkUser_int',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to='api.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkTask_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_id', to='api.status'),
        ),
    ]
