# Generated by Django 3.1.2 on 2020-10-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201023_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_log',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkAssignment_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to='api.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fkElement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Element_id', to='api.element'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
