# Generated by Django 3.1.2 on 2020-10-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201028_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestquotation',
            old_name='fkUser_int',
            new_name='fkUser_id',
        ),
    ]
