# Generated by Django 3.1.2 on 2020-10-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201017_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='fkInventory_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_id', to='api.inventory'),
        ),
    ]
