# Generated by Django 3.1.2 on 2020-10-29 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201028_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='fkUser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkUser_id', to='api.user'),
        ),
    ]
