version: '3.3'
services:
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minventoryuser -d minventory_db || exit 1"]
      interval: 3s
      timeout: 30s
      retries: 3
    container_name: "minventory-db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    environment:
          POSTGRES_USER: minventoryuser
          POSTGRES_PASSWORD: minventory123
          POSTGRES_DB: minventory_db
    networks:
      - minventory-network

  api:
    depends_on:
      db:
        condition: service_healthy
    build: .
    command: bash -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - .:/minventory
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - minventory-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@minventory.com"
      PGADMIN_DEFAULT_PASSWORD: "minventory123"
      PGADMIN_LISTEN_PORT: 5454
    ports:
      - 5454:5454/tcp
    depends_on:
      db:
        condition: service_healthy
    networks:
      - minventory-network

networks: 
  minventory-network:
    driver: bridge
